import _ from 'lodash';

export default function() {
    return _.shuffle([
        { value: 'Ace', suite: 'heart' },
        { value: 2, suite: 'heart' },
        { value: 3, suite: 'heart' },
        { value: 4, suite: 'heart' },
        { value: 5, suite: 'heart' },
        { value: 6, suite: 'heart' },
        { value: 7, suite: 'heart' },
        { value: 8, suite: 'heart' },
        { value: 9, suite: 'heart' },
        { value: 10, suite: 'heart' },
        { value: 'Jack', suite: 'heart' },
        { value: 'Queen', suite: 'heart' },
        { value: 'King', suite: 'heart' },
        { value: 'Ace', suite: 'heart' },
        { value: 2, suite: 'spade' },
        { value: 3, suite: 'spade' },
        { value: 4, suite: 'spade' },
        { value: 5, suite: 'spade' },
        { value: 6, suite: 'spade' },
        { value: 7, suite: 'spade' },
        { value: 8, suite: 'spade' },
        { value: 9, suite: 'spade' },
        { value: 10, suite: 'spade' },
        { value: 'Jack', suite: 'spade' },
        { value: 'Queen', suite: 'spade' },
        { value: 'King', suite: 'spade' },
        { value: 'Ace', suite: 'diamond' },
        { value: 2, suite: 'diamond' },
        { value: 3, suite: 'diamond' },
        { value: 4, suite: 'diamond' },
        { value: 5, suite: 'diamond' },
        { value: 6, suite: 'diamond' },
        { value: 7, suite: 'diamond' },
        { value: 8, suite: 'diamond' },
        { value: 9, suite: 'diamond' },
        { value: 10, suite: 'diamond' },
        { value: 'Jack', suite: 'diamond' },
        { value: 'Queen', suite: 'diamond' },
        { value: 'King', suite: 'diamond' },
        { value: 'Ace', suite: 'clover' },
        { value: 2, suite: 'clover' },
        { value: 3, suite: 'clover' },
        { value: 4, suite: 'clover' },
        { value: 5, suite: 'clover' },
        { value: 6, suite: 'clover' },
        { value: 7, suite: 'clover' },
        { value: 8, suite: 'clover' },
        { value: 9, suite: 'clover' },
        { value: 10, suite: 'clover' },
        { value: 'Jack', suite: 'clover' },
        { value: 'Queen', suite: 'clover' },
        { value: 'King', suite: 'clover' },
    ]);
}